Created Uganda Annual Culture Forum page
danielmatama/matama-capstone pull request #1
Opened 2023-01-03 08:35 UTC by danielmatama

I created the mobile version of the Uganda Annual Culture homepage using HTML and styled it using CSS
I made the mobile version of the about page
I made the desktop version of the home page and the desktop version of the about page
I made links to connect the pages and a dropdown button for mobile versions.
I input the speakers' section dynamically in javascript

2023-01-04 07:56 UTC, levy002 reviewed
## Hello @danielmatama 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that doesn't run linter on the PR. Kindly make sure the linters are running on your PR to check your code.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-04 10:00 UTC, fobadara requested changes
Hi @danielmatama, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Linters are passing
✅ Project looks professional

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 10:00 UTC, fobadara commented on README.md
> +## 💻 Getting Started <a name="getting-started"></a>
[REQUIRED] I can't seem to find the link to your video presentation. I had to type in the link to view the page. Kindly include it

2023-01-04 10:00 UTC, fobadara commented on README.md
> +
[REQUIRED] Could you credit Cindy shin for the design? Don't forget to include a link to her work

2023-01-04 10:00 UTC, fobadara commented on index.html
> +        <a href="about-page/about.html" class="ax">About</a>
[REQIRED] Kindly ensure that the link to the about page is working. It currently redirects to a 404 page

2023-01-04 10:00 UTC, fobadara commented on about-page/about.html
> +<script src="scripts.js"></script>
[REQUIRED] Kindly ensure that your footers contain a logo on the left and text on the right. One of the aims of this project is to teach you to follow project requirements.

[REQUIRED] I noticed that you are not using semantic tags like section, article, and footer among others in a lot of places. Kindly fix this.
[REQUIRED]For desktop screens the about page should have a dark background while the homepage should have white bacckground

2023-01-04 10:00 UTC, fobadara commented on about-page/about.html
> +          <img src="images/facebook.png" alt="twitter-icon" class="twitter">
[REQUIRED] The content for your home and about page is overlaying.

![new](https://user-images.githubusercontent.com/62938735/210522176-a6cd5e31-eab6-4a83-9124-ec08a6a47908.gif)

2023-01-04 10:00 UTC, fobadara commented on scripts.js
> +  <img src="images/checked.png" alt="" class="checked">
[REQUIRED] Kindly arrange the needed data in an array of objects and create the elements from it. Something like this:

```
const speakerList = [ { name: "Speaker Name",... } ]

for (let i= ......) {
  const element = <p>speaker[I].name</p>
...........................
}
```

2023-01-05 19:30 UTC, binhussen requested changes
Hi @danielmatama , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Suggested changes
- Kindly be sure your link is not broken 👍👍


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-05 19:30 UTC, binhussen commented on index.html
> +        </li>
- Kindly update your navigation link as your previous code reviewer suggested, 
  - when you start from your current directory start with`./` and then to the folder or file
  - if you went to back start `../` 👌👌 
about directory `./about-page/about.html` 👌👍

2023-01-05 19:30 UTC, binhussen commented on about-page/about.html
> +          <a class="nav-link active home" aria-current="page" href="/home/matama/matama-capstone/index.html">Home</a>
- Kindly update your navigation link as your previous code reviewer suggested,
  - when you start from your current directory start with./ and then to the folder or file
  - if you went to back start ../ 👌👌
home directory`../index.html` 👌👍

2023-01-05 19:30 UTC, binhussen commented on README.md
> +
- [Optional] Great Job for adding an author in "Acknowledgements" section, I think it is better to make it with appropriate links together like  "  to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)."😉👍

2023-01-06 09:56 UTC, KayLemba approved these changes
[# STATUS: APPROVED :green_circle: :clap: 

Hello  @danielmatama         , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Descriptive P.R
- [x] Unit tests are passing 





 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]

2023-01-06 09:56 UTC, KayLemba commented on index.html
> +    <!-- <a class="navbar-brand" href="#">navbar</a> -->
[OPTIONAL] Please consider deleting unused code for it makes your code base look untidy

2023-01-06 09:56 UTC, KayLemba commented on index.html
> +<!-- <script src="scripts.js"></script> -->
[OPTIONAL] Please consider deleting unused code for it makes you code base look untidy

2023-01-06 09:56 UTC, KayLemba commented on about.html
> +    <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
[OPTIONAL] Please kindly delete unused code fot it makes your code base look untidy

2023-01-06 10:41 UTC, merged